# Справочник загрязняющих веществ и ПДК
# Источник: внутренний справочник + ГН 2.1.6.3492-17

SUBSTANCES = [
    # === Стандартные вещества (ГН) ===
    {"code": "0301", "name": "Азота диоксид (NO2)", "pdk_mr": 0.2, "pdk_ss": 0.04, "hazard_class": 3, "F": 1.0},
    {"code": "0304", "name": "Азота оксид (NO)", "pdk_mr": 0.4, "pdk_ss": 0.06, "hazard_class": 3, "F": 1.0},
    {"code": "0330", "name": "Серы диоксид (SO2)", "pdk_mr": 0.5, "pdk_ss": 0.05, "hazard_class": 3, "F": 1.0},
    {"code": "0337", "name": "Углерода оксид (CO)", "pdk_mr": 5.0, "pdk_ss": 3.0, "hazard_class": 4, "F": 1.0},
    {"code": "2902", "name": "Пыль неорганическая (до 20% SiO2)", "pdk_mr": 0.5, "pdk_ss": 0.15, "hazard_class": 3, "F": 3.0},
    {"code": "2908", "name": "Пыль неорганическая (20–70% SiO2)", "pdk_mr": 0.3, "pdk_ss": 0.1, "hazard_class": 3, "F": 3.0},
    {"code": "0328", "name": "Сажа (углерод чёрный)", "pdk_mr": 0.15, "pdk_ss": 0.05, "hazard_class": 3, "F": 3.0},
    {"code": "1325", "name": "Формальдегид", "pdk_mr": 0.05, "pdk_ss": 0.01, "hazard_class": 2, "F": 1.0},
    {"code": "0703", "name": "Бенз(а)пирен", "pdk_mr": None, "pdk_ss": 0.000001, "hazard_class": 1, "F": 1.0},
    {"code": "1042", "name": "Аммиак", "pdk_mr": 0.2, "pdk_ss": 0.04, "hazard_class": 4, "F": 1.0},
    {"code": "1071", "name": "Фтористый водород", "pdk_mr": 0.02, "pdk_ss": 0.005, "hazard_class": 2, "F": 1.0},
    {"code": "0410", "name": "Метан", "pdk_mr": 50.0, "pdk_ss": None, "hazard_class": None, "F": 1.0},

    # === Справочник предприятия (Вещества новый) ===
    {"code": "01", "name": "Уайт-спирит", "pdk_mr": 0.2, "pdk_ss": None, "hazard_class": 4, "F": 1.0},
    {"code": "03", "name": "Пары масла", "pdk_mr": 1.0, "pdk_ss": None, "hazard_class": 4, "F": 1.0},
    {"code": "03а", "name": "Аммиачная селитра", "pdk_mr": 1.5, "pdk_ss": None, "hazard_class": 4, "F": 3.0},
    {"code": "04", "name": "Аммиак", "pdk_mr": 0.2, "pdk_ss": None, "hazard_class": 4, "F": 1.0},
    {"code": "05", "name": "Метилметакрилат", "pdk_mr": 0.01, "pdk_ss": None, "hazard_class": 4, "F": 1.0},
    {"code": "08", "name": "Сольвент", "pdk_mr": 0.1, "pdk_ss": None, "hazard_class": 3, "F": 1.0},
    {"code": "08п", "name": "Пыль термопластов", "pdk_mr": 0.1, "pdk_ss": None, "hazard_class": 3, "F": 1.0},
    {"code": "09", "name": "Аэрозоль свинца", "pdk_mr": 0.002, "pdk_ss": None, "hazard_class": 1, "F": 1.0},
    {"code": "10", "name": "Оксид алюминия", "pdk_mr": 2.0, "pdk_ss": None, "hazard_class": 3, "F": 1.0},
    {"code": "10щ", "name": "Аэрозоль щелочи", "pdk_mr": 0.01, "pdk_ss": None, "hazard_class": 2, "F": 1.0},
    {"code": "11", "name": "Азотная кислота", "pdk_mr": 0.4, "pdk_ss": None, "hazard_class": 3, "F": 1.0},
    {"code": "11н", "name": "Нитрил акриловой кислоты", "pdk_mr": 0.03, "pdk_ss": None, "hazard_class": 2, "F": 1.0},
    {"code": "12", "name": "Барий хлорид", "pdk_mr": 0.004, "pdk_ss": None, "hazard_class": None, "F": 1.0},
    {"code": "13", "name": "Стирол", "pdk_mr": 0.003, "pdk_ss": None, "hazard_class": 2, "F": 1.0},
    {"code": "14", "name": "Изобутилен", "pdk_mr": 10.0, "pdk_ss": None, "hazard_class": 4, "F": 1.0},
    {"code": "15", "name": "Капролактам", "pdk_mr": 10.0, "pdk_ss": None, "hazard_class": 3, "F": 1.0},
    {"code": "16", "name": "α-метилстирол", "pdk_mr": 0.04, "pdk_ss": None, "hazard_class": 3, "F": 1.0},
    {"code": "16ц", "name": "Оксид цинка", "pdk_mr": 0.05, "pdk_ss": None, "hazard_class": 3, "F": 1.0},
    {"code": "17", "name": "Масло минеральное", "pdk_mr": 0.05, "pdk_ss": None, "hazard_class": 4, "F": 1.0},
    {"code": "18", "name": "Дивинил", "pdk_mr": 3.0, "pdk_ss": None, "hazard_class": 4, "F": 1.0},
    {"code": "19", "name": "Аммоний сульфат", "pdk_mr": 10.0, "pdk_ss": None, "hazard_class": 3, "F": 1.0},
    {"code": "20", "name": "Изопрен", "pdk_mr": 0.02, "pdk_ss": None, "hazard_class": 3, "F": 1.0},
    {"code": "22", "name": "Серная кислота", "pdk_mr": 0.3, "pdk_ss": None, "hazard_class": 2, "F": 1.0},
    {"code": "23", "name": "Диоктилфталат", "pdk_mr": 0.02, "pdk_ss": None, "hazard_class": 3, "F": 1.0},
    {"code": "24", "name": "Алифатические углеводороды", "pdk_mr": 1.0, "pdk_ss": None, "hazard_class": None, "F": 1.0},
    {"code": "27", "name": "Ксилол", "pdk_mr": 0.2, "pdk_ss": None, "hazard_class": 3, "F": 1.0},
    {"code": "31", "name": "Спирт этиловый", "pdk_mr": 5.0, "pdk_ss": None, "hazard_class": 4, "F": 1.0},
    {"code": "34", "name": "Оксиды азота", "pdk_mr": 0.085, "pdk_ss": None, "hazard_class": 2, "F": 1.0},
    {"code": "38", "name": "Оксид углерода", "pdk_mr": 5.0, "pdk_ss": None, "hazard_class": 4, "F": 1.0},
    {"code": "42", "name": "Окись этилена", "pdk_mr": 0.03, "pdk_ss": None, "hazard_class": None, "F": 1.0},
    {"code": "44", "name": "Синтетическое моющее средство", "pdk_mr": 0.5, "pdk_ss": None, "hazard_class": None, "F": 3.0},
    {"code": "44с", "name": "Пыль соли", "pdk_mr": 0.5, "pdk_ss": None, "hazard_class": 3, "F": 3.0},
    {"code": "45", "name": "Ацетон", "pdk_mr": 0.35, "pdk_ss": None, "hazard_class": 4, "F": 1.0},
    {"code": "51", "name": "Пыль полипропилена", "pdk_mr": 0.1, "pdk_ss": None, "hazard_class": 3, "F": 1.0},
    {"code": "53", "name": "Пыль полиэтилена", "pdk_mr": 0.1, "pdk_ss": None, "hazard_class": 3, "F": 3.0},
    {"code": "55", "name": "Пыль цементная", "pdk_mr": 0.3, "pdk_ss": None, "hazard_class": 3, "F": 3.0},
    {"code": "57", "name": "Сажа", "pdk_mr": 0.15, "pdk_ss": None, "hazard_class": 3, "F": 1.0},
    {"code": "58", "name": "Сварочный аэрозоль", "pdk_mr": 0.2, "pdk_ss": None, "hazard_class": 4, "F": 3.0},
    {"code": "63", "name": "Натрий гидроксид", "pdk_mr": 0.01, "pdk_ss": None, "hazard_class": 2, "F": 1.0},
    {"code": "64", "name": "Натрий карбонат (кальцинированная сода)", "pdk_mr": 0.04, "pdk_ss": None, "hazard_class": 3, "F": 1.0},
    {"code": "64у", "name": "Уксусная кислота", "pdk_mr": 0.2, "pdk_ss": None, "hazard_class": 3, "F": 1.0},
    {"code": "65", "name": "Фториды плохо растворимые", "pdk_mr": 0.03, "pdk_ss": None, "hazard_class": 2, "F": 1.0},
    {"code": "66", "name": "Аэрозоль эмульсола", "pdk_mr": 1.0, "pdk_ss": None, "hazard_class": None, "F": 1.0},
    {"code": "66м", "name": "Аэрозоль масла", "pdk_mr": 1.0, "pdk_ss": None, "hazard_class": 4, "F": 1.0},
    {"code": "75", "name": "Фенолы", "pdk_mr": 0.01, "pdk_ss": None, "hazard_class": 2, "F": 1.0},
    {"code": "76", "name": "Эпихлоргидрид", "pdk_mr": 0.2, "pdk_ss": None, "hazard_class": None, "F": 1.0},
    {"code": "78", "name": "Амины", "pdk_mr": 0.1, "pdk_ss": None, "hazard_class": 2, "F": 1.0},
    {"code": "86", "name": "Оксид железа", "pdk_mr": 0.2, "pdk_ss": None, "hazard_class": 3, "F": 3.0},
    {"code": "88", "name": "Пыль алюминиевая", "pdk_mr": 0.2, "pdk_ss": None, "hazard_class": None, "F": 3.0},
    {"code": "90", "name": "Органические кислоты", "pdk_mr": 0.2, "pdk_ss": None, "hazard_class": 2, "F": 1.0},
    {"code": "97", "name": "Карбоновые кислоты", "pdk_mr": 0.2, "pdk_ss": None, "hazard_class": 2, "F": 1.0},
    {"code": "97п", "name": "Пыль асбеста", "pdk_mr": 0.3, "pdk_ss": None, "hazard_class": None, "F": 3.0},
    {"code": "98", "name": "Меркаптаны", "pdk_mr": 0.6, "pdk_ss": None, "hazard_class": 2, "F": 1.0},
    {"code": "99", "name": "Карбональные соединения", "pdk_mr": 0.01, "pdk_ss": None, "hazard_class": 2, "F": 1.0},
    {"code": "100", "name": "Пыль зерновая", "pdk_mr": 0.3, "pdk_ss": None, "hazard_class": 3, "F": 3.0},
    {"code": "100п", "name": "Пыль поливинилхлорида", "pdk_mr": 0.1, "pdk_ss": None, "hazard_class": 2, "F": 1.0},
    {"code": "101", "name": "Пыль металлическая", "pdk_mr": 0.2, "pdk_ss": None, "hazard_class": 3, "F": 3.0},
    {"code": "102", "name": "Пыль абразивная", "pdk_mr": 0.2, "pdk_ss": None, "hazard_class": 3, "F": 3.0},
    {"code": "103", "name": "Акролеин", "pdk_mr": 0.03, "pdk_ss": None, "hazard_class": None, "F": 1.0},
    {"code": "104", "name": "Альдегиды", "pdk_mr": 0.04, "pdk_ss": None, "hazard_class": 3, "F": 1.0},
    {"code": "105", "name": "Сульфид ангидрид", "pdk_mr": 0.5, "pdk_ss": None, "hazard_class": 3, "F": 1.0},
    {"code": "106", "name": "Оксиды серы", "pdk_mr": 0.5, "pdk_ss": None, "hazard_class": 3, "F": 1.0},
    {"code": "107", "name": "Пары аммиачной воды", "pdk_mr": 0.2, "pdk_ss": None, "hazard_class": 4, "F": 1.0},
    {"code": "107ф", "name": "Фосфорная кислота", "pdk_mr": 1.0, "pdk_ss": None, "hazard_class": 2, "F": 1.0},
    {"code": "108", "name": "Бен(а)пирен", "pdk_mr": 0.00001, "pdk_ss": None, "hazard_class": 1, "F": 1.0},
    {"code": "110", "name": "Натрий гидроксид (раствор)", "pdk_mr": 0.5, "pdk_ss": None, "hazard_class": 2, "F": 1.0},
    {"code": "111", "name": "Эпоксиэтан", "pdk_mr": 0.3, "pdk_ss": None, "hazard_class": 3, "F": 1.0},
    {"code": "111щ", "name": "Щёлковая пыль", "pdk_mr": 0.4, "pdk_ss": None, "hazard_class": 3, "F": 2.0},
    {"code": "112", "name": "Пары бензина", "pdk_mr": 5.0, "pdk_ss": None, "hazard_class": 4, "F": 1.0},
    {"code": "113", "name": "Пыль древесная", "pdk_mr": 0.01, "pdk_ss": None, "hazard_class": 3, "F": 3.0},
    {"code": "114", "name": "Пыль неорганическая", "pdk_mr": 0.3, "pdk_ss": None, "hazard_class": 3, "F": 3.0},
    {"code": "115", "name": "Аэрозоль сульфата уранила", "pdk_mr": 0.015, "pdk_ss": None, "hazard_class": 1, "F": 1.0},
    {"code": "115к", "name": "Пыль клинкера", "pdk_mr": 0.5, "pdk_ss": None, "hazard_class": 3, "F": 3.0},
    {"code": "115т", "name": "Твёрдые частицы", "pdk_mr": 0.15, "pdk_ss": None, "hazard_class": 3, "F": 1.0},
    {"code": "115у", "name": "Уран", "pdk_mr": 0.0005, "pdk_ss": None, "hazard_class": 1, "F": 1.0},
    {"code": "116", "name": "Пыль руды", "pdk_mr": 0.3, "pdk_ss": None, "hazard_class": 3, "F": 3.0},
    {"code": "117", "name": "Пыль фосфоритная", "pdk_mr": 0.3, "pdk_ss": None, "hazard_class": 3, "F": 3.0},
    {"code": "118", "name": "Углеводороды", "pdk_mr": 1.0, "pdk_ss": None, "hazard_class": 4, "F": 1.0},
    {"code": "119", "name": "Фтористый водород", "pdk_mr": 0.012, "pdk_ss": None, "hazard_class": 2, "F": 1.0},
    {"code": "120", "name": "Хлористый водород", "pdk_mr": 0.2, "pdk_ss": None, "hazard_class": 2, "F": 1.0},
    {"code": "121", "name": "Оксид кремния", "pdk_mr": 0.002, "pdk_ss": None, "hazard_class": 3, "F": 1.0},
    {"code": "122", "name": "Хлористый кальций", "pdk_mr": 0.2, "pdk_ss": None, "hazard_class": 2, "F": 1.0},
    {"code": "123", "name": "Оксид марганца", "pdk_mr": 0.005, "pdk_ss": None, "hazard_class": 2, "F": 2.0},
    {"code": "124", "name": "Пыль сульфида натрия", "pdk_mr": 0.2, "pdk_ss": None, "hazard_class": 2, "F": 3.0},
    {"code": "125", "name": "Пыль золы", "pdk_mr": 0.3, "pdk_ss": None, "hazard_class": 3, "F": 3.0},
    {"code": "126", "name": "Пропен (пропилен)", "pdk_mr": 3.0, "pdk_ss": None, "hazard_class": 3, "F": 1.0},
    {"code": "126к", "name": "Пыль керамзита", "pdk_mr": 0.3, "pdk_ss": None, "hazard_class": 3, "F": 3.0},
    {"code": "127", "name": "Пыль комбикорма", "pdk_mr": 0.01, "pdk_ss": None, "hazard_class": 3, "F": 3.0},
    {"code": "128", "name": "Пыль угольная", "pdk_mr": 0.3, "pdk_ss": None, "hazard_class": 3, "F": 3.0},
    {"code": "129", "name": "Пыль мучная", "pdk_mr": 0.3, "pdk_ss": None, "hazard_class": 3, "F": 3.0},
    {"code": "129а", "name": "Алканы", "pdk_mr": 1.0, "pdk_ss": None, "hazard_class": 4, "F": 1.0},
    {"code": "129с", "name": "Пыль сульфата натрия", "pdk_mr": 0.3, "pdk_ss": None, "hazard_class": 3, "F": 3.0},
    {"code": "130", "name": "Пыль шрота", "pdk_mr": 0.01, "pdk_ss": None, "hazard_class": None, "F": 3.0},
    {"code": "131", "name": "Пыль животного происхождения", "pdk_mr": 0.03, "pdk_ss": None, "hazard_class": 3, "F": 3.0},
    {"code": "131о", "name": "Пыль органическая", "pdk_mr": 0.5, "pdk_ss": None, "hazard_class": None, "F": 3.0},
    {"code": "133", "name": "Сульфиды", "pdk_mr": 1.0, "pdk_ss": None, "hazard_class": 3, "F": 1.0},
    {"code": "135", "name": "Ацетальдегид", "pdk_mr": 0.01, "pdk_ss": None, "hazard_class": 3, "F": 2.0},
    {"code": "138", "name": "Пентан", "pdk_mr": 100.0, "pdk_ss": None, "hazard_class": 4, "F": 1.0},
    {"code": "140", "name": "Этен (этилен)", "pdk_mr": 3.0, "pdk_ss": None, "hazard_class": 3, "F": 1.0},
    {"code": "143", "name": "Хлор", "pdk_mr": 1.0, "pdk_ss": None, "hazard_class": 3, "F": 1.0},
    {"code": "144", "name": "Соляная кислота", "pdk_mr": 0.2, "pdk_ss": None, "hazard_class": 2, "F": 1.0},
    {"code": "144к", "name": "Пыль карбоната натрия", "pdk_mr": 2.0, "pdk_ss": None, "hazard_class": 3, "F": 3.0},
    {"code": "145", "name": "Пыль силиката натрия", "pdk_mr": 2.0, "pdk_ss": None, "hazard_class": 3, "F": 3.0},
    {"code": "146", "name": "Пыль сажи", "pdk_mr": 0.15, "pdk_ss": None, "hazard_class": 3, "F": 3.0},
    {"code": "148", "name": "Аэрозоль полиэтилена", "pdk_mr": 1.0, "pdk_ss": None, "hazard_class": 3, "F": 1.0},
    {"code": "149", "name": "Микроорганизмы", "pdk_mr": 0.01, "pdk_ss": None, "hazard_class": 3, "F": 1.0},
    {"code": "150", "name": "Формальдегид", "pdk_mr": 0.035, "pdk_ss": None, "hazard_class": 2, "F": 1.0},
    {"code": "151", "name": "Олова оксид", "pdk_mr": 0.02, "pdk_ss": None, "hazard_class": 3, "F": 1.0},
    {"code": "151д", "name": "Дибутилфталат", "pdk_mr": 0.5, "pdk_ss": None, "hazard_class": 2, "F": 1.0},
    {"code": "154", "name": "Оксид азота (двуокись азота)", "pdk_mr": 1.6, "pdk_ss": None, "hazard_class": 3, "F": 1.0},
    {"code": "174", "name": "Карбонат натрия", "pdk_mr": 2.0, "pdk_ss": None, "hazard_class": 3, "F": 1.0},
    {"code": "175", "name": "Сульфид натрия", "pdk_mr": 0.2, "pdk_ss": None, "hazard_class": 2, "F": 1.0},
    {"code": "185", "name": "Оксид хрома", "pdk_mr": 0.0015, "pdk_ss": None, "hazard_class": 1, "F": 1.0},
    {"code": "200", "name": "Пропан", "pdk_mr": 60.0, "pdk_ss": None, "hazard_class": 4, "F": 1.0},
    {"code": "201", "name": "Сернистый ангидрид (сернистый газ)", "pdk_mr": 0.05, "pdk_ss": None, "hazard_class": 3, "F": 1.0},
    {"code": "202", "name": "Этилмеркаптан", "pdk_mr": 0.00003, "pdk_ss": None, "hazard_class": 2, "F": 1.0},
    {"code": "203", "name": "Хлоропрен", "pdk_mr": 0.02, "pdk_ss": None, "hazard_class": 2, "F": 1.0},
    {"code": "204", "name": "Сероводород", "pdk_mr": 0.008, "pdk_ss": None, "hazard_class": 2, "F": 2.0},
    {"code": "205", "name": "Метан", "pdk_mr": 50.0, "pdk_ss": None, "hazard_class": 4, "F": 1.0},
    {"code": "206", "name": "Сумма метана и этана", "pdk_mr": 3.0, "pdk_ss": None, "hazard_class": 4, "F": 1.0},
    {"code": "207", "name": "Сумма пропана и пропилена", "pdk_mr": 3.0, "pdk_ss": None, "hazard_class": 4, "F": 1.0},
    {"code": "208", "name": "Бутан", "pdk_mr": 200.0, "pdk_ss": None, "hazard_class": 4, "F": 1.0},
    {"code": "211", "name": "Одорант СПМ (сумма природных меркаптанов)", "pdk_mr": 0.00005, "pdk_ss": None, "hazard_class": 2, "F": 1.0},
    {"code": "215", "name": "Хлорид натрия", "pdk_mr": 0.15, "pdk_ss": None, "hazard_class": 3, "F": 1.0},
    {"code": "215п", "name": "Пыль огарка", "pdk_mr": 0.5, "pdk_ss": None, "hazard_class": 3, "F": 3.0},
    {"code": "216", "name": "Акрилонитрил", "pdk_mr": 0.1, "pdk_ss": None, "hazard_class": 2, "F": 1.0},
    {"code": "217", "name": "Полиакриламид", "pdk_mr": 0.01, "pdk_ss": None, "hazard_class": 2, "F": 1.0},
    {"code": "233", "name": "Ванадий", "pdk_mr": 0.5, "pdk_ss": None, "hazard_class": 2, "F": 1.0},
    {"code": "234", "name": "Пыль карбамида", "pdk_mr": 0.06, "pdk_ss": None, "hazard_class": 3, "F": 3.0},
    {"code": "238", "name": "Аэрозоль краски", "pdk_mr": 0.5, "pdk_ss": None, "hazard_class": 4, "F": 1.0},
    {"code": "285", "name": "Полиэтиленполиамин", "pdk_mr": 0.001, "pdk_ss": None, "hazard_class": 2, "F": 1.0},
    {"code": "300", "name": "Бутилацетат", "pdk_mr": 0.1, "pdk_ss": None, "hazard_class": None, "F": 1.0},
    {"code": "311", "name": "Этилбензол", "pdk_mr": 0.02, "pdk_ss": None, "hazard_class": 3, "F": 1.0},
    {"code": "315", "name": "Свинец", "pdk_mr": 0.001, "pdk_ss": None, "hazard_class": 1, "F": 1.0},
    {"code": "316", "name": "Хлористый цинк", "pdk_mr": 0.005, "pdk_ss": None, "hazard_class": 3, "F": 1.0},
    {"code": "334", "name": "Спирт н-бутиловый", "pdk_mr": 0.1, "pdk_ss": None, "hazard_class": None, "F": 1.0},
    {"code": "335", "name": "Сера элементарная", "pdk_mr": 0.07, "pdk_ss": None, "hazard_class": 3, "F": 3.0},
    {"code": "351", "name": "Метанол", "pdk_mr": 1.0, "pdk_ss": None, "hazard_class": 3, "F": 1.0},
    {"code": "361", "name": "Толуол", "pdk_mr": 0.6, "pdk_ss": None, "hazard_class": 3, "F": 1.0},
    {"code": "362", "name": "Этилцеллозольв", "pdk_mr": 0.7, "pdk_ss": None, "hazard_class": None, "F": 1.0},
    {"code": "404", "name": "Сероуглерод", "pdk_mr": 0.03, "pdk_ss": None, "hazard_class": 2, "F": 1.0},
    {"code": "422", "name": "Цианистый водород (Синильная кислота)", "pdk_mr": 0.01, "pdk_ss": None, "hazard_class": 2, "F": 1.0},
    {"code": "444", "name": "Метилмеркаптан", "pdk_mr": 0.8, "pdk_ss": None, "hazard_class": 4, "F": 1.0},
    {"code": "499", "name": "Бутиловый спирт", "pdk_mr": 0.1, "pdk_ss": None, "hazard_class": 3, "F": 1.0},
    {"code": "649", "name": "Диметилдиоксан", "pdk_mr": 0.01, "pdk_ss": None, "hazard_class": 3, "F": 1.0},
    {"code": "679", "name": "Диметиловый эфир", "pdk_mr": 0.2, "pdk_ss": None, "hazard_class": 2, "F": 1.0},
    {"code": "712", "name": "Пыль хлопковая", "pdk_mr": 0.5, "pdk_ss": None, "hazard_class": 3, "F": 3.0},
    {"code": "777", "name": "Пыль гипса", "pdk_mr": 0.5, "pdk_ss": None, "hazard_class": 3, "F": 3.0},
    {"code": "845", "name": "Пары растворителя", "pdk_mr": 0.07, "pdk_ss": None, "hazard_class": 4, "F": 1.0},
    {"code": "858", "name": "Дихлорфторметан", "pdk_mr": 100.0, "pdk_ss": None, "hazard_class": 4, "F": 1.0},
    {"code": "859", "name": "Пары гидрофторуглерода", "pdk_mr": 100.0, "pdk_ss": None, "hazard_class": None, "F": 1.0},
    {"code": "887", "name": "Едкий натрий (Натрий гидроксид)", "pdk_mr": 0.01, "pdk_ss": None, "hazard_class": 2, "F": 1.0},
    {"code": "900", "name": "Винил хлористый", "pdk_mr": 0.005, "pdk_ss": None, "hazard_class": 2, "F": 1.0},
    {"code": "902", "name": "Пыль известняка", "pdk_mr": 0.5, "pdk_ss": None, "hazard_class": 3, "F": 3.0},
    {"code": "902и", "name": "Пыль извести", "pdk_mr": 0.3, "pdk_ss": None, "hazard_class": 3, "F": 3.0},
    {"code": "903", "name": "Пыль сланца", "pdk_mr": 0.5, "pdk_ss": None, "hazard_class": 3, "F": 3.0},
    {"code": "961", "name": "Метилацетат", "pdk_mr": 0.07, "pdk_ss": None, "hazard_class": 4, "F": 1.0},
    {"code": "990", "name": "Сернокислое железо (железа сульфат)", "pdk_mr": 0.01, "pdk_ss": None, "hazard_class": 3, "F": 1.0},
    {"code": "991", "name": "Сульфат железа (Железный купорос)", "pdk_mr": 0.007, "pdk_ss": None, "hazard_class": 3, "F": 1.0},
    {"code": "Э", "name": "Этанол", "pdk_mr": 0.4, "pdk_ss": None, "hazard_class": None, "F": 1.0},
]
